# Generated by Django 2.0.1 on 2018-01-22 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
