# Generated by Django 2.0.1 on 2018-01-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='place',
            field=models.CharField(default='h2m', max_length=200),
        ),
    ]
