# Generated by Django 2.0.1 on 2018-01-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0003_auto_20180121_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Invitation',
        ),
    ]
