# Generated by Django 2.0.1 on 2018-01-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0004_auto_20180121_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='author',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='published_date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='title',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='text',
        ),
        migrations.AddField(
            model_name='invitation',
            name='guest',
            field=models.CharField(default='Invitadillo', max_length=200),
        ),
        migrations.AddField(
            model_name='invitation',
            name='place',
            field=models.CharField(default='h2m', max_length=200),
        ),
    ]
