# Generated by Django 2.0.1 on 2018-01-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0005_auto_20180121_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='descr',
            field=models.TextField(),
        ),
    ]
