# Generated by Django 2.0.1 on 2018-01-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0006_auto_20180121_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_type', models.CharField(default='single', max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(blank=True, max_length=70)),
                ('mobile', models.CharField(max_length=20)),
                ('invitation', models.CharField(max_length=200)),
            ],
        ),
    ]
