# Generated by Django 2.0.1 on 2018-02-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0008_auto_20180205_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fiesta', max_length=50)),
                ('date', models.DateTimeField(blank=True)),
                ('place', models.URLField()),
                ('host', models.CharField(default='Carolina', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hw.Confirmation')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Invitado', max_length=50)),
                ('name', models.CharField(max_length=70)),
                ('mail', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='invitation',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='link',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='place',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.AddField(
            model_name='person',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hw.Invitation'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hw.Invitation'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hw.Event'),
        ),
    ]
