# Generated by Django 2.0.1 on 2018-02-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0009_auto_20180206_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='host',
            new_name='event',
        ),
    ]
