# Generated by Django 2.0.1 on 2018-02-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0011_auto_20180207_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='pic',
            field=models.ImageField(default='hw/static/images/pokeball.png', upload_to='hw/static/images'),
        ),
    ]
