# Generated by Django 2.0.1 on 2018-02-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0013_auto_20180222_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='status',
            field=models.CharField(choices=[('Abailable', 'A'), ('Taken', 'T')], max_length=15),
        ),
    ]
