# Generated by Django 2.0.1 on 2018-02-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0014_auto_20180222_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='status',
            field=models.CharField(choices=[('Available', 'A'), ('Taken', 'T')], max_length=15),
        ),
    ]
