# Generated by Django 2.0.1 on 2018-02-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0015_auto_20180222_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Guest',
        ),
    ]
