# Generated by Django 2.0.1 on 2018-02-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0018_auto_20180226_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
