# Generated by Django 2.0.1 on 2018-02-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0019_auto_20180226_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='role',
        ),
    ]
