# Generated by Django 2.0.1 on 2018-02-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0020_remove_guest_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hw.Confirmation')),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='slug',
            field=models.SlugField(default='gift'),
        ),
        migrations.AddField(
            model_name='confirmationdetail',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hw.Gift'),
        ),
    ]
