# Generated by Django 2.0.1 on 2018-03-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0021_auto_20180226_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='invitation',
        ),
        migrations.RemoveField(
            model_name='confirmationdetail',
            name='confirmation',
        ),
        migrations.RemoveField(
            model_name='confirmationdetail',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='confirmation',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='event',
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
        migrations.DeleteModel(
            name='ConfirmationDetail',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
