# Generated by Django 2.0.1 on 2018-03-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0022_auto_20180301_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='active',
            new_name='going',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='active',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='active',
        ),
        migrations.AddField(
            model_name='invitation',
            name='inv_type',
            field=models.CharField(choices=[('Giver', 'G'), ('Single', 'S'), ('Couple', 'S')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
