# Generated by Django 2.0.1 on 2018-03-01 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0023_auto_20180301_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hw.Guest'),
        ),
    ]
