# Generated by Django 2.0.1 on 2018-03-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0025_auto_20180302_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='pic',
            field=models.TextField(),
        ),
    ]
